// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package regexmatch.actions;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;

public class RegexMatch extends CustomJavaAction<java.lang.String>
{
	private java.lang.String RegexPattern;
	private java.lang.String InputString;
	private java.lang.Long OutputGroup;

	public RegexMatch(IContext context, java.lang.String RegexPattern, java.lang.String InputString, java.lang.Long OutputGroup)
	{
		super(context);
		this.RegexPattern = RegexPattern;
		this.InputString = InputString;
		this.OutputGroup = OutputGroup;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		Pattern regex = Pattern.compile(RegexPattern);
		Matcher matches = regex.matcher(InputString);
		String match = null;
		
		// Loop through matches
		for(int x = -1; x < OutputGroup.intValue(); x++) {
			if(!matches.find()) break;
		}
		match = matches.group();
		
		return match;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "RegexMatch";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
